### PR TITLE
Allennlp version 1.0.0

### PR DESCRIPTION
**Pull request by jasonge27**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged) [ no need since version is changed]
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FernandezMathieu** [comment]
@conda-forge-admin

**Comment by FernandezMathieu** [comment]
@conda-forge-linter restart ci

**Comment by FernandezMathieu** [comment]
@jasonge27 why did you stop workin' on this ?

**Comment by jasonge27** [comment]
> @jasonge27 why did you stop workin' on this ?

Hey @FernandezMathieu thanks for taking a look. I was side-tracked by something else. I'll find time for it this month or early Jan.

**Comment by h-vetinari** [comment]
For anyone subscribed to this thread - I've started an attempt to carry on this work in #12

**Pull request closed without merging**
