### PR TITLE
v1.5.0 for spacy 3.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Try relaxing the pin because, in conjunction with https://github.com/conda-forge/spacy-model-en_core_web-feedstock/issues/11, this is causing issues for https://github.com/conda-forge/allennlp-semparse-feedstock/pull/2 (and perhaps others)

### CODE REVIEW

**Comment by h-vetinari** [comment]
@dirkgr, is there planned to be a spacy 3 compatible release in the 1.x series? Or are there some upstream patches we could add here to make it compatible?

**Comment by dirkgr** [comment]
We don't have that plan, but if it makes things easier for you, we could
back-port those changes to the 1.x branch. It's not a lot of work.

**Comment by h-vetinari** [comment]
> 
> We don't have that plan, but if it makes things easier for you, we could back-port those changes to the 1.x branch. It's not a lot of work.

If that's not too much work, that would be awesome! Not being compatible with the newest versions can lead to issues with dependency resolution, as illustrated e.g. by https://github.com/conda-forge/spacy-model-en_core_web-feedstock/issues/11.

**Comment by dirkgr** [comment]
Version 1.5 is out today!

**Pull request merged**
